// ignore_for_file: type=lint
enum FilterType {
  BothStockAndPriority,
  OnlyPriority,
  AllDistributors,
  MappedDistributors,
  NonMappedDistributors,
  OnlyInStock,
  IncludeOutOfStockProducts,
  AllScheme,
  OnlySchemeProduct,
  AllExpiry,
  HiddenExpiry,
  VisibleExpiry,
  AllCompanies,
  CompanyA,
  CompanyB,
  CompanyC,
  searchBy,
  distributors,
  stock,
  scheme,
  expiry,
  byCompany,
  FilteredStoreIds,
}
