import 'package:flutter/material.dart';
import 'package:pharmarack/packages/core_flutter/localization/app_localizations.dart';

/// Extension on BuildContext to get localized strings
///   Usage: `context.localizedString.request`
///   here `request` is the autogenerated constant based on `intl_en.arb` file
extension ApplocalizationContext on BuildContext {
  AppLocalizations get localizedString => AppLocalizations.of(this)!;
}
